//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFollowedDocumentWebPart.MyFollowedDocuments {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class MyFollowedDocuments {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(MyFollowedDocuments target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::MyFollowedDocumentWebPart.MyFollowedDocuments.MyFollowedDocuments @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    $(function () {\r\n\r\n        var myF" +
                        "ollow = new MyFollowed();\r\n        myFollow.displayLoading();\r\n\r\n        SP.SOD." +
                        "executeOrDelayUntilScriptLoaded(function () {\r\n            SP.SOD.registerSod(\'S" +
                        "P.UserProfiles.js\', SP.Utilities.Utility.getLayoutsPageUrl(\"SP.UserProfiles.js\")" +
                        ");\r\n            SP.SOD.executeFunc(\'SP.UserProfiles.js\', \'SP.UserProfiles.People" +
                        "Manager\', function () { myFollow.init(); });\r\n        }, \"SP.js\");\r\n\r\n    });\r\n\r" +
                        "\n    function MyFollowed() {\r\n\r\n        this.wrapper = $(\"#myFollowedDocWrapper\"" +
                        ");\r\n\r\n        this.init = function () {\r\n            this.CheckMySite();\r\n      " +
                        "  };\r\n\r\n        this.displayLoading = function () {\r\n            this.wrapper.ap" +
                        "pend($(\'<img src=\"\' + _spPageContextInfo.webServerRelativeUrl + \'/_layouts/15/im" +
                        "ages/gears_anv4.gif\" style=\"width: 15px;\"/><span style=\"margin-left: 10px;vertic" +
                        "al-align: 3px;\">loading</span>\'));\r\n        }\r\n\r\n        this.CheckMySite = func" +
                        "tion () {\r\n            this.getPersonalUrl().done(function (result, url) {\r\n    " +
                        "            this.wrapper.empty();\r\n                if (result) this.getMyFollowe" +
                        "dDocuments(this.wrapper);\r\n                else this.wrapper.append($(\'<div><a h" +
                        "ref=\"\' + url + \'\">Click here to enable this feature</a></div>\'));\r\n            }" +
                        ".bind(this));\r\n        }\r\n\r\n        this.getPersonalUrl = function () {\r\n       " +
                        "     var d = $.Deferred();\r\n            var context = SP.ClientContext.get_curre" +
                        "nt();\r\n            var peopleManager = new SP.UserProfiles.PeopleManager(context" +
                        ");\r\n            userProfileProperties = peopleManager.getMyProperties();\r\n      " +
                        "      context.load(userProfileProperties, \'PersonalUrl\');\r\n            context.e" +
                        "xecuteQueryAsync(\r\n                function () {\r\n                    var url = " +
                        "userProfileProperties.get_personalUrl();\r\n                    if (url.indexOf(\'P" +
                        "erson.aspx\') == -1) {\r\n                        // user has a MySite already crea" +
                        "ted - fetch documents\r\n                        d.resolve(true);\r\n               " +
                        "     } else {\r\n                        // user does not have MySite created - di" +
                        "splay link\r\n                        d.resolve(false, url);\r\n                    " +
                        "}\r\n                }.bind(this),\r\n                this.onQueryFailed\r\n          " +
                        "  );\r\n\r\n            return d.promise();\r\n        };\r\n\r\n        this.getMyFollowe" +
                        "dDocuments = function (wrapper) {\r\n            var uri = _spPageContextInfo.webS" +
                        "erverRelativeUrl + \"/_api/social.following/my/followed(types=2)\";\r\n\r\n           " +
                        " $.ajax({\r\n                url: uri,\r\n                headers: { \"Accept\": \"appl" +
                        "ication/json; odata=verbose\" },\r\n                success: function (data) {\r\n   " +
                        "                 var items = [];\r\n                    $.each(data.d.Followed.res" +
                        "ults, function (k, v) {\r\n\r\n                        var id = \"fDoc_\" + k;\r\n      " +
                        "                  items.push(\'<div id=\"\' + id + \'\"><span class=\"ms-contentFollow" +
                        "ing-itemTitle\"> \\\r\n                                    <span style=\"height: 16px" +
                        "; width: 16px; position: relative; display: inline-block; overflow: hidden;\" cla" +
                        "ss=\"s4-clust ms-promotedActionButton-icon\">\\\r\n                                  " +
                        "      <a href=\"#\" onclick=\"StopFollowDocument(\\\'\' + id + \'\\\',\\\'\' + v.ContentUri " +
                        "+ \'\\\');\">\\\r\n                                            <img src=\"/_layouts/15/i" +
                        "mages/NowFollowing.11x11x32.png?rev=23\" alt=\"Follow\" style=\"vertical-align:3px;\"" +
                        "/></a>\\\r\n                                    </span>\\\r\n                         " +
                        "           <a href=\"\' + v.ContentUri + \'\" class=\"js-contentFollowing-itemLink ms" +
                        "-textLarge ms-recs-titleLink\" >\' + v.Name + \'</a></span></div>\');\r\n\r\n           " +
                        "             //            <div class=\"js-contentFollowing-itemUrlDiv\"><a href=\"" +
                        "\'+ v.ContentUri + \'>\' + v.ContentUri + \'</a>\');\r\n                        //     " +
                        "               items.push(\"<li id=\'\" + v.ContentUri + \"\'>\" + v.Name + \"</li>\");\r" +
                        "\n                    });\r\n\r\n                    $(\"<div/>\", { \"class\": \"\", html:" +
                        " items.join(\"\") }).appendTo(wrapper);\r\n                }\r\n            });\r\n     " +
                        "   }\r\n\r\n        this.onQueryFailed = function () {\r\n            console.error(\"E" +
                        "rror\");\r\n        };\r\n\r\n    }\r\n\r\n    /// required to ensure latest FormDigestValu" +
                        "e to prevent 403 error\r\n    function getFormDigest(webUrl) {\r\n        return $.a" +
                        "jax({\r\n            url: webUrl + \"/_api/contextinfo\",\r\n            method: \"POST" +
                        "\",\r\n            headers: { \"Accept\": \"application/json; odata=verbose\" }\r\n      " +
                        "  });\r\n    }\r\n\r\n    function StopFollowDocument(id, docUri) {\r\n\r\n        if (con" +
                        "firm(\"You are about to remove that document from your list of followed documents" +
                        ". Click OK to proceed.\")) {\r\n\r\n\r\n            getFormDigest(_spPageContextInfo.we" +
                        "bServerRelativeUrl).then(function (data) {\r\n\r\n                //http://<siteColl" +
                        "ection>/<site>/_api/social.following/stopfollowing(ActorType=1,ContentUri=@v,Id=" +
                        "null)?@v=\'http://server/Shared%20Documents/fileName.docx\'\r\n                //var" +
                        " uri = \"http://\" + window.location.hostname + \"/_api/social.following/stopfollow" +
                        "ing(ActorType=1,ContentUri=@v,Id=null)?@v=\'\" + docUri + \"\'\";\r\n                va" +
                        "r uri = _spPageContextInfo.webServerRelativeUrl + \"/_api/social.following/stopfo" +
                        "llowing\";\r\n\r\n                var body = JSON.stringify({\r\n                    \"a" +
                        "ctor\": {\r\n                        \"__metadata\": { \"type\": \"SP.Social.SocialActor" +
                        "Info\" },\r\n                        \"ActorType\": 1,\r\n                        \"Cont" +
                        "entUri\": docUri,\r\n                        \"Id\": null\r\n                    }\r\n   " +
                        "             });\r\n\r\n                var headers = {\r\n                    \"accept" +
                        "\": \"application/json; odata=verbose\",\r\n                    \"content-type\": \"appl" +
                        "ication/json;odata=verbose\",\r\n                    \"X-RequestDigest\": data.d.GetC" +
                        "ontextWebInformation.FormDigestValue\r\n                };\r\n\r\n                $.aj" +
                        "ax({\r\n                    url: uri,\r\n                    method: \"POST\",\r\n      " +
                        "              headers: headers,\r\n                    data: body,\r\n              " +
                        "      success: function (data) {\r\n                        $(\"#\" + id).remove();\r" +
                        "\n                    },\r\n                    error: function (xhr, status, error" +
                        ") {\r\n                        console.error(status);\r\n                        con" +
                        "sole.error(error);\r\n                    }\r\n                });\r\n\r\n\r\n\r\n          " +
                        "  });\r\n        }\r\n\r\n    }\r\n</script>\r\n\r\n<div id=\"myFollowedDocWrapper\">\r\n</div>\r" +
                        "\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
